-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.flights
(
    id integer NOT NULL,
    year integer,
    month integer,
    day integer,
    day_of_week integer,
    airline text COLLATE pg_catalog."default",
    flight_number integer,
    tail_number text COLLATE pg_catalog."default",
    origin_airport text COLLATE pg_catalog."default",
    destination_airport text COLLATE pg_catalog."default",
    scheduled_departure integer,
    departure_time integer,
    departure_delay integer,
    taxi_out integer,
    wheels_off integer,
    scheduled_time integer,
    elapsed_time integer,
    air_time integer,
    distance integer,
    wheels_on integer,
    taxi_in integer,
    scheduled_arrival integer,
    arrival_time integer,
    arrival_delay integer,
    diverted integer,
    cancelled integer,
    cancellation_reason text COLLATE pg_catalog."default",
    air_system_delay integer,
    security_delay integer,
    airline_delay integer,
    late_aircraft_delay integer,
    weather_delay integer,
    CONSTRAINT flights_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.airline
(
    "IATA_code" text NOT NULL,
    airline text,
    PRIMARY KEY ("IATA_code")
);

CREATE TABLE IF NOT EXISTS public.airports
(
    "IATA_code" text NOT NULL,
    airport text,
    latitude real,
    longitude real,
    city_a integer,
    PRIMARY KEY ("IATA_code")
);

CREATE TABLE IF NOT EXISTS public.city
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name text,
    state text,
    country text,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY (airline)
    REFERENCES public.airline ("IATA_code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY (origin_airport)
    REFERENCES public.airports ("IATA_code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.flights
    ADD FOREIGN KEY (destination_airport)
    REFERENCES public.airports ("IATA_code") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.airports
    ADD FOREIGN KEY (city_a)
    REFERENCES public.city (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;